on:
  pull_request:
    branches:
    - main
    paths:
    - ResumeWebpage/*

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: aws deploy
        run: aws s3 cp ${{ github.workspace }}/ResumeWebpage/* s3://brianfukanostagingresume/
      - name: aws verify
        run: if curl 'http://brianfukanostagingresume.s3-website.us-east-2.amazonaws.com' 2>&1>/dev/null; then exit 0; else exit 1; fi

      
